Repository openedx/edx-toggles, pull requests merged in 2021-01, with the labels that each got.

#80 [BD-21] Deprecate waffle namespaces
  CHANGELOG.rst
  edx_toggles/__init__.py
  edx_toggles/tests/test_testutils.py
  edx_toggles/tests/test_waffle.py
  edx_toggles/toggles/__future__.py
  edx_toggles/toggles/__init__.py
  edx_toggles/toggles/internal/waffle/legacy.py
Labels: blended, needs triage

#109 Fix "toggle_type" column of Setting toggles in state report
  CHANGELOG.rst
  scripts/toggles.py
Labels: core committer, open-source-contribution, waiting on author

#112 [FIX] feature_toogle_annotations.yaml reference link in how_to doc
  docs/how_to/documenting_new_feature_toggles.rst
Labels: needs triage, open-source-contribution
